name: Publish-Module
on: [workflow_dispatch]

jobs:
  build:
    name: Publish-Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish-Module
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: .\Publish-Module.ps1
        shell: pwsh
